export const COURSE_CODES = {
  MATH: "MATH",
  STAT: "STAT",
  COMSCI: "CS",
  FINANCE: "AFM",
  ENGLISH: "ENGL",
  COMMUNICATION: "SPCOM",
  ENTREPRENEURSHIP: "BET",
  SCIENCE: "SCI",
  HEALTH: "AHS",
  CLASSICAL: "CLAS",
  COMMERCE: "COMM",
  MUSIC: "MUSIC",
};
